import { useEffect, useRef, useState } from "react";
import { APIError, Experience, ExperienceDetail, addExperienceNote, exportExperiences, getExperiences } from "../lib/api";
import { useI18n, formatDate, nodeLabel } from "../lib/i18n";
import { AppLink } from "../app/router";

export function ExperiencePanel({ taskID }: { taskID: string }) {
 const { t } = useI18n(); const [data, setData] = useState<ExperienceDetail | null>(null); const [error, setError] = useState(""); const [page, setPage] = useState(1); const [refresh, setRefresh] = useState(0); const [busy, setBusy] = useState(false);
 useEffect(() => { setData(null); }, [taskID, page]);
 useEffect(() => { const controller = new AbortController(); const read = () => getExperiences(taskID, page, "", controller.signal).then(value => { setData(value); setError(""); }).catch(reason => { if (!controller.signal.aborted) setError(String(reason)); }); read(); const timer = window.setInterval(read, 2000); return () => { controller.abort(); window.clearInterval(timer); }; }, [taskID, page, refresh]);
 async function runExport() { setBusy(true); try { const value = await exportExperiences(taskID); setData(current => current && { ...current, export: value }); setError(""); } catch (reason) { setError(String(reason)); } finally { setBusy(false); } }
 return <section className="surface experience-panel"><div className="section-heading"><h2>{t("experience.title")}</h2><AppLink href="/experiences">{t("experience.find")}</AppLink></div><p>{t("experience.context")}</p>{error && <p className="notice warning" role="alert">{error}</p>}{data && <><div className="experience-export"><button className="button" disabled={busy || data.export.generation === 0} onClick={runExport}>{busy ? t("experience.exporting") : t("experience.export")}</button><span role="status">{data.export.error ? t("experience.exportFailed") : data.export.generation > data.export.exported_generation ? t("experience.pendingExport") : data.export.generation > 0 ? t("experience.exported") : ""}</span>{data.export.path && <code>{data.export.path}</code>}</div>{data.experiences.length === 0 ? <p>{t("experience.empty")}</p> : data.experiences.map(value => <ExperienceCard key={value.experience_id} value={value} onChanged={() => setRefresh(v => v + 1)} />)}<ExperiencePagination page={page} more={data.has_next} onPage={setPage} /></>}</section>;
}
export function ExperiencePagination({ page, more, onPage }: { page: number; more: boolean; onPage: (page: number) => void }) { const { t } = useI18n(); return <div className="pagination"><button className="button" disabled={page <= 1} onClick={() => onPage(page - 1)}>{t("list.previous")}</button><span>{t("list.page", { page })}</span><button className="button" disabled={!more} onClick={() => onPage(page + 1)}>{t("list.next")}</button></div>; }
export function ExperienceCard({ value, onChanged, history = false }: { value: Experience; onChanged?: () => void; history?: boolean }) {
 const { language, t } = useI18n(); const [note, setNote] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [versions, setVersions] = useState<ExperienceDetail | null>(null); const [historyPage, setHistoryPage] = useState(1); const [showHistory, setShowHistory] = useState(false);
 const pending = useRef<{ id: string; text: string; value: Experience } | null>(null);
 useEffect(() => { if (!showHistory) return; const controller = new AbortController(); getExperiences(value.task_id, historyPage, value.experience_id, controller.signal).then(setVersions).catch(reason => { if (!controller.signal.aborted) setError(String(reason)); }); return () => controller.abort(); }, [showHistory, historyPage, value.task_id, value.experience_id, value.revision]);
 async function saveNote() { setBusy(true); if (!pending.current) pending.current = { id: `note-${crypto.randomUUID()}`, text: note.trim(), value }; try { await addExperienceNote(pending.current.value, pending.current.text, pending.current.id); pending.current = null; setNote(""); setError(""); onChanged?.(); } catch (reason) { if (reason instanceof APIError && reason.failure.workflow_write_state === "not_committed") { pending.current = null; onChanged?.(); } setError(String(reason)); } finally { setBusy(false); } }
 return <article className="experience-card"><header><h3>{value.content.title}</h3><span className={`experience-status ${value.content.status}`}>{t(`experience.${value.content.status}`)}</span></header><p className="experience-meta">{nodeLabel(value.stage, language)} → {nodeLabel(value.updated_stage, language)} · r{value.revision} · {formatDate(value.updated_at, language)}</p><dl>{(["problem", "cause", "resolution", "basis", "applicability", "next_checks"] as const).map(key => <div key={key}><dt>{t(`experience.${key}`)}</dt><dd>{value.content[key]}</dd></div>)}</dl><details><summary>{t("experience.references")}</summary><ul>{value.content.references.map((ref, i) => <li key={i}><strong>{ref.kind}</strong> <code>{ref.locator}</code><p>{ref.summary}</p></li>)}</ul>{value.projects.map(project => <p key={project.key}><AppLink href={`/experiences?project=${encodeURIComponent(project.group)}`}>{project.key}</AppLink> <code>{project.path}</code></p>)}<small>{t("experience.recordedContent")}: <code>{value.content_digest}</code></small><p>{value.change_reason}</p></details><h4>{t("experience.notes")}</h4>{value.user_notes.length === 0 ? <p>{t("experience.noNotes")}</p> : value.user_notes.map((item, index) => <blockquote key={index}><p>{item.text}</p><small>{formatDate(item.created_at, language)}</small></blockquote>)}{error && <p role="alert" className="notice warning">{error}</p>}{onChanged && <form onSubmit={event => { event.preventDefault(); void saveNote(); }}><label>{t("experience.addNote")}<textarea value={note} disabled={busy || pending.current !== null} maxLength={8192} onChange={event => setNote(event.target.value)} /></label><button className="button" disabled={busy || !note.trim()}>{busy ? t("experience.saving") : pending.current ? t("experience.retryNote") : t("experience.saveNote")}</button></form>}{!history && value.revision > 1 && <><button className="button" onClick={() => setShowHistory(v => !v)}>{t("experience.history")}</button>{showHistory && versions && <div className="experience-history">{versions.experiences.map(version => <ExperienceCard key={version.revision} value={version} history />)}<ExperiencePagination page={historyPage} more={versions.has_next} onPage={setHistoryPage} /></div>}</>}</article>;
}
