import { useEffect, useState } from "react";
import { AppLink, navigate } from "../app/router";
import { ExperiencePage, searchExperiences } from "../lib/api";
import { useI18n, nodeLabel } from "../lib/i18n";
import { ExperienceCard, ExperiencePagination } from "../components/ExperiencePanel";
export function ExperiencesPage() {
 const { t, language } = useI18n(); const query = new URLSearchParams(window.location.search); const text = query.get("text") ?? ""; const project = query.get("project") ?? ""; const page = Number(query.get("page") ?? "1");
 const [data, setData] = useState<ExperiencePage | null>(null); const [error, setError] = useState("");
 useEffect(() => { const controller = new AbortController(); setData(null); searchExperiences(new URLSearchParams({ text, project, page: String(page) }), controller.signal).then(value => { setData(value); setError(""); }).catch(reason => { if (!controller.signal.aborted) setError(String(reason)); }); return () => controller.abort(); }, [text, project, page]);
 return <div className="page-stack"><header className="page-header"><div><p className="eyebrow">Dev Flow</p><h1>{t("experience.title")}</h1><p>{t("experience.findHelp")}</p></div></header><form className="surface experience-filters" key={`${text}/${project}`} onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); navigate(`/experiences?${new URLSearchParams({ text: String(form.get("text") ?? ""), project: String(form.get("project") ?? ""), page: "1" })}`); }}><label>{t("experience.searchLabel")}<input name="text" defaultValue={text} maxLength={512} placeholder={t("experience.searchHint")} /></label><label>{t("list.repository")}<input name="project" defaultValue={project} maxLength={4096} placeholder={t("experience.projectHint")} /></label><button className="button primary">{t("list.apply")}</button></form>{error && <p className="notice warning" role="alert">{error}</p>}{data && <>{data.items.length === 0 && <section className="surface">{t("experience.empty")}</section>}{data.items.map(item => <section className="surface" key={`${item.experience.task_id}/${item.experience.experience_id}`}><AppLink href={`/tasks/${encodeURIComponent(item.experience.task_id)}`}>{item.task_summary}</AppLink><p>{nodeLabel(item.task_state, language)} {item.archived && `· ${t("list.archived")}`}</p><ExperienceCard value={item.experience} /></section>)}<ExperiencePagination page={data.page} more={data.has_next} onPage={next => navigate(`/experiences?${new URLSearchParams({ text, project, page: String(next) })}`)} /></>}</div>;
}
